# --- Use these corrected paths ---

music_directory      "/home/ambr/music"
playlist_directory   "/home/ambr/.mpd/playlists"
db_file              "/home/ambr/.mpd/mpd.db"
log_file             "/home/ambr/.mpd/mpd.log"
pid_file             "/home/ambr/.mpd/mpd.pid"
state_file           "/home/ambr/.mpd/mpdstate"

# --- The rest of your configuration ---

bind_to_address "127.0.0.1"

audio_output {
    type "pulse"
    name "pulse audio"
#    device "pulse"
    mixer_type "hardware"
}

audio_output {
    type "fifo"
    name "my_fifo"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
}
